site_name: Mkdocstrings Python Generator
docs_dir: docs
site_dir: dist/mkdocs_site

# gives a link on each documentation page directly to edit that page in Github!
repo_url: https://github.com/couling/MkdocstringsPythonGenerator
edit_uri: edit/main/docs/


# Enable the theme "Material"
theme:
  name: "material"
  custom_dir: overrides
  features:
    - content.action.edit
    - navigation.tracking
    - navigation.sections
    - navigation.indexes

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - toc:
      permalink: true

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 2
          show_source: false
          show_submodules: false
        selection:
          docstring_style: sphinx
- mkdocstrings-python-generator:
    nav_heading:
      - Reference
    base: ../source
    search:
      - ../source/mkdocstrings_python_generator

watch:
  - docs
  - ../source/mkdocstrings_python_generator

extra:
  version:
    provider: mike
